language: ruby

rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head

bundler_args: '--without debug'

cache: bundler

sudo: false

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head

script: bundle exec rake
