language: ruby

rvm:
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.4
  - 2.4.2
  - jruby
  - ruby-head

bundler_args: '--without debug'

cache: bundler

sudo: false

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: ruby-head

script: bundle exec rake
